<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="12" ignored="0" total="42" passed="24" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-17T20:18:09 EDT" name="Suite" finished-at="2025-05-17T20:22:13 EDT" duration-ms="244168">
    <groups>
      <group name="datadriven">
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" name="testLogin" class="testCases.TC02_Login"/>
      </group> <!-- datadriven -->
      <group name="regression">
        <method signature="TC006_AddAffiliate.login()[pri:0, instance:testCases.TC006_AddAffiliate@1d1f7216]" name="login" class="testCases.TC006_AddAffiliate"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4ebea12c]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2a1edad4]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC05__AddToWishList.addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@7fcbe147]" name="addToWishList" class="testCases.TC05__AddToWishList"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
        <method signature="TC006_AddAffiliate.login()[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" name="login" class="testCases.TC006_AddAffiliate"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@71e5f61d]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC05__AddToWishList.addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" name="addToWishList" class="testCases.TC05__AddToWishList"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
        <method signature="TC006_AddAffiliate.login()[pri:0, instance:testCases.TC006_AddAffiliate@4204541c]" name="login" class="testCases.TC006_AddAffiliate"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@6a62689d]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@4602c2a9]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC05__AddToWishList.addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@79e18e38]" name="addToWishList" class="testCases.TC05__AddToWishList"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4ebea12c]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2a1edad4]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@71e5f61d]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
        <method signature="TC01_LaunchApplication.testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@6a62689d]" name="testLaunchApplication" class="testCases.TC01_LaunchApplication"/>
        <method signature="TC02_Login.testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" name="testLogin" class="testCases.TC02_Login"/>
        <method signature="TC03_AddToCart.testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@4602c2a9]" name="testAddToCart" class="testCases.TC03_AddToCart"/>
        <method signature="TC_04_CompletePurchase.checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" name="checkOut" class="testCases.TC_04_CompletePurchase"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2025-05-17T20:18:09 EDT" name="firefoxTest" finished-at="2025-05-17T20:19:58 EDT" duration-ms="109098">
      <class name="testCases.TC05__AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" started-at="2025-05-17T20:19:49 EDT" name="openApp" finished-at="2025-05-17T20:19:55 EDT" duration-ms="5829" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" started-at="2025-05-17T20:19:55 EDT" name="addToWishList" finished-at="2025-05-17T20:19:55 EDT" duration-ms="891" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05__AddToWishList.addToWishList(TC05__AddToWishList.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToWishList -->
        <test-method retried="true" signature="addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" started-at="2025-05-17T20:19:55 EDT" name="addToWishList" finished-at="2025-05-17T20:19:56 EDT" duration-ms="734" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05__AddToWishList.addToWishList(TC05__AddToWishList.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToWishList -->
        <test-method signature="addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" started-at="2025-05-17T20:19:56 EDT" name="addToWishList" finished-at="2025-05-17T20:19:57 EDT" duration-ms="319" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05__AddToWishList.addToWishList(TC05__AddToWishList.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05__AddToWishList@fd46303]" started-at="2025-05-17T20:19:57 EDT" name="closeApp" finished-at="2025-05-17T20:19:58 EDT" duration-ms="1279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05__AddToWishList -->
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:29 EDT" name="openApp" finished-at="2025-05-17T20:19:35 EDT" duration-ms="6204" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:37 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:19:39 EDT" duration-ms="2429" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ezinneokorbassey5@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:39 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:19:41 EDT" duration-ms="2184" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[egobekee@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:41 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:19:44 EDT" duration-ms="2124" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:44 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:19:46 EDT" duration-ms="2150" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:46 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:19:47 EDT" duration-ms="1781" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@51df223b]" started-at="2025-05-17T20:19:47 EDT" name="closeApp" finished-at="2025-05-17T20:19:49 EDT" duration-ms="1292" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC006_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" started-at="2025-05-17T20:18:10 EDT" name="openApp" finished-at="2025-05-17T20:18:33 EDT" duration-ms="23116" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="login()[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" started-at="2025-05-17T20:18:33 EDT" name="login" finished-at="2025-05-17T20:18:35 EDT" duration-ms="2771" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC006_AddAffiliate.login(TC006_AddAffiliate.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method retried="true" signature="login()[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" started-at="2025-05-17T20:18:36 EDT" name="login" finished-at="2025-05-17T20:18:36 EDT" duration-ms="84" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC006_AddAffiliate.login(TC006_AddAffiliate.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="login()[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" started-at="2025-05-17T20:18:36 EDT" name="login" finished-at="2025-05-17T20:18:36 EDT" duration-ms="76" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected exception.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC006_AddAffiliate.login(TC006_AddAffiliate.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC006_AddAffiliate@5bda80bf]" started-at="2025-05-17T20:18:36 EDT" name="closeApp" finished-at="2025-05-17T20:18:41 EDT" duration-ms="4862" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC006_AddAffiliate -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@71e5f61d]" started-at="2025-05-17T20:18:41 EDT" name="openApp" finished-at="2025-05-17T20:18:56 EDT" duration-ms="14940" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@71e5f61d]" started-at="2025-05-17T20:18:56 EDT" name="testLaunchApplication" finished-at="2025-05-17T20:18:56 EDT" duration-ms="38" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@71e5f61d]" started-at="2025-05-17T20:18:56 EDT" name="closeApp" finished-at="2025-05-17T20:18:59 EDT" duration-ms="3110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" started-at="2025-05-17T20:18:59 EDT" name="openApp" finished-at="2025-05-17T20:19:12 EDT" duration-ms="12936" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" started-at="2025-05-17T20:19:12 EDT" name="testAddToCart" finished-at="2025-05-17T20:19:13 EDT" duration-ms="1435" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method retried="true" signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" started-at="2025-05-17T20:19:13 EDT" name="testAddToCart" finished-at="2025-05-17T20:19:14 EDT" duration-ms="1112" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" started-at="2025-05-17T20:19:14 EDT" name="testAddToCart" finished-at="2025-05-17T20:19:15 EDT" duration-ms="79" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@2ce86164]" started-at="2025-05-17T20:19:15 EDT" name="closeApp" finished-at="2025-05-17T20:19:17 EDT" duration-ms="2461" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC_04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" started-at="2025-05-17T20:19:17 EDT" name="openApp" finished-at="2025-05-17T20:19:25 EDT" duration-ms="7717" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" started-at="2025-05-17T20:19:25 EDT" name="checkOut" finished-at="2025-05-17T20:19:26 EDT" duration-ms="1186" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" started-at="2025-05-17T20:19:26 EDT" name="checkOut" finished-at="2025-05-17T20:19:27 EDT" duration-ms="767" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" started-at="2025-05-17T20:19:27 EDT" name="checkOut" finished-at="2025-05-17T20:19:27 EDT" duration-ms="346" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC_04_CompletePurchase@5e8f9e2d]" started-at="2025-05-17T20:19:28 EDT" name="closeApp" finished-at="2025-05-17T20:19:29 EDT" duration-ms="1584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC_04_CompletePurchase -->
    </test> <!-- firefoxTest -->
    <test started-at="2025-05-17T20:18:09 EDT" name="chromeTest" finished-at="2025-05-17T20:22:04 EDT" duration-ms="235062">
      <class name="testCases.TC05__AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05__AddToWishList@7fcbe147]" started-at="2025-05-17T20:21:51 EDT" name="openApp" finished-at="2025-05-17T20:21:55 EDT" duration-ms="3872" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@7fcbe147]" started-at="2025-05-17T20:21:55 EDT" name="addToWishList" finished-at="2025-05-17T20:22:02 EDT" duration-ms="7739" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05__AddToWishList@7fcbe147]" started-at="2025-05-17T20:22:02 EDT" name="closeApp" finished-at="2025-05-17T20:22:04 EDT" duration-ms="1759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05__AddToWishList -->
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:31 EDT" name="openApp" finished-at="2025-05-17T20:21:34 EDT" duration-ms="2467" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:34 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:37 EDT" duration-ms="2906" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ezinneokorbassey5@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:37 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:39 EDT" duration-ms="2601" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[egobekee@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:39 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:43 EDT" duration-ms="3994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:43 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:47 EDT" duration-ms="3987" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:47 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:50 EDT" duration-ms="2824" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@44c79f32]" started-at="2025-05-17T20:21:50 EDT" name="closeApp" finished-at="2025-05-17T20:21:51 EDT" duration-ms="599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC006_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC006_AddAffiliate@1d1f7216]" started-at="2025-05-17T20:18:09 EDT" name="openApp" finished-at="2025-05-17T20:18:20 EDT" duration-ms="10724" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="login()[pri:0, instance:testCases.TC006_AddAffiliate@1d1f7216]" started-at="2025-05-17T20:18:20 EDT" name="login" finished-at="2025-05-17T20:18:33 EDT" duration-ms="12669" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC006_AddAffiliate@1d1f7216]" started-at="2025-05-17T20:18:33 EDT" name="closeApp" finished-at="2025-05-17T20:18:34 EDT" duration-ms="885" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC006_AddAffiliate -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@4ebea12c]" started-at="2025-05-17T20:18:34 EDT" name="openApp" finished-at="2025-05-17T20:18:37 EDT" duration-ms="3715" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@4ebea12c]" started-at="2025-05-17T20:18:37 EDT" name="testLaunchApplication" finished-at="2025-05-17T20:18:39 EDT" duration-ms="2037" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@4ebea12c]" started-at="2025-05-17T20:18:39 EDT" name="closeApp" finished-at="2025-05-17T20:18:41 EDT" duration-ms="1618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@2a1edad4]" started-at="2025-05-17T20:18:41 EDT" name="openApp" finished-at="2025-05-17T20:18:46 EDT" duration-ms="4695" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@2a1edad4]" started-at="2025-05-17T20:18:46 EDT" name="testAddToCart" finished-at="2025-05-17T20:18:51 EDT" duration-ms="5419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@2a1edad4]" started-at="2025-05-17T20:18:51 EDT" name="closeApp" finished-at="2025-05-17T20:18:52 EDT" duration-ms="924" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC_04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" started-at="2025-05-17T20:18:52 EDT" name="openApp" finished-at="2025-05-17T20:18:58 EDT" duration-ms="5511" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" started-at="2025-05-17T20:18:58 EDT" name="checkOut" finished-at="2025-05-17T20:19:08 EDT" duration-ms="10670" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" started-at="2025-05-17T20:19:08 EDT" name="checkOut" finished-at="2025-05-17T20:20:20 EDT" duration-ms="71361" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" started-at="2025-05-17T20:20:20 EDT" name="checkOut" finished-at="2025-05-17T20:21:30 EDT" duration-ms="70673" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC_04_CompletePurchase@6256ac4f]" started-at="2025-05-17T20:21:31 EDT" name="closeApp" finished-at="2025-05-17T20:21:31 EDT" duration-ms="510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC_04_CompletePurchase -->
    </test> <!-- chromeTest -->
    <test started-at="2025-05-17T20:18:09 EDT" name="edgeTest" finished-at="2025-05-17T20:22:13 EDT" duration-ms="244168">
      <class name="testCases.TC05__AddToWishList">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC05__AddToWishList@79e18e38]" started-at="2025-05-17T20:22:01 EDT" name="openApp" finished-at="2025-05-17T20:22:05 EDT" duration-ms="3548" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="addToWishList()[pri:0, instance:testCases.TC05__AddToWishList@79e18e38]" started-at="2025-05-17T20:22:05 EDT" name="addToWishList" finished-at="2025-05-17T20:22:12 EDT" duration-ms="6938" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToWishList -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC05__AddToWishList@79e18e38]" started-at="2025-05-17T20:22:12 EDT" name="closeApp" finished-at="2025-05-17T20:22:13 EDT" duration-ms="1319" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC05__AddToWishList -->
      <class name="testCases.TC02_Login">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:40 EDT" name="openApp" finished-at="2025-05-17T20:21:44 EDT" duration-ms="3843" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:44 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:48 EDT" duration-ms="3888" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ezinneokorbassey5@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:48 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:51 EDT" duration-ms="3084" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[egobekee@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:51 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:54 EDT" duration-ms="2841" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[sid@cloudberry.services]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Test123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:54 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:21:57 EDT" duration-ms="3162" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[apushedwoman@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method signature="testLogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:21:57 EDT" name="testLogin" data-provider="LoginData" finished-at="2025-05-17T20:22:00 EDT" duration-ms="2870" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hichamkhachiai@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hicham123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC02_Login@3e2822]" started-at="2025-05-17T20:22:00 EDT" name="closeApp" finished-at="2025-05-17T20:22:01 EDT" duration-ms="1384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC02_Login -->
      <class name="testCases.TC006_AddAffiliate">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC006_AddAffiliate@4204541c]" started-at="2025-05-17T20:18:10 EDT" name="openApp" finished-at="2025-05-17T20:18:22 EDT" duration-ms="12753" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="login()[pri:0, instance:testCases.TC006_AddAffiliate@4204541c]" started-at="2025-05-17T20:18:22 EDT" name="login" finished-at="2025-05-17T20:18:33 EDT" duration-ms="10400" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC006_AddAffiliate@4204541c]" started-at="2025-05-17T20:18:33 EDT" name="closeApp" finished-at="2025-05-17T20:18:35 EDT" duration-ms="2311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC006_AddAffiliate -->
      <class name="testCases.TC01_LaunchApplication">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC01_LaunchApplication@6a62689d]" started-at="2025-05-17T20:18:35 EDT" name="openApp" finished-at="2025-05-17T20:18:41 EDT" duration-ms="6311" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testLaunchApplication()[pri:0, instance:testCases.TC01_LaunchApplication@6a62689d]" started-at="2025-05-17T20:18:41 EDT" name="testLaunchApplication" finished-at="2025-05-17T20:18:41 EDT" duration-ms="25" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLaunchApplication -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC01_LaunchApplication@6a62689d]" started-at="2025-05-17T20:18:41 EDT" name="closeApp" finished-at="2025-05-17T20:18:44 EDT" duration-ms="2395" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC01_LaunchApplication -->
      <class name="testCases.TC03_AddToCart">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC03_AddToCart@4602c2a9]" started-at="2025-05-17T20:18:44 EDT" name="openApp" finished-at="2025-05-17T20:18:50 EDT" duration-ms="6433" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="testAddToCart()[pri:0, instance:testCases.TC03_AddToCart@4602c2a9]" started-at="2025-05-17T20:18:50 EDT" name="testAddToCart" finished-at="2025-05-17T20:18:56 EDT" duration-ms="5914" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddToCart -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC03_AddToCart@4602c2a9]" started-at="2025-05-17T20:18:56 EDT" name="closeApp" finished-at="2025-05-17T20:18:58 EDT" duration-ms="1997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC03_AddToCart -->
      <class name="testCases.TC_04_CompletePurchase">
        <test-method is-config="true" signature="openApp(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" started-at="2025-05-17T20:18:58 EDT" name="openApp" finished-at="2025-05-17T20:19:03 EDT" duration-ms="5101" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[windows]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" started-at="2025-05-17T20:19:03 EDT" name="checkOut" finished-at="2025-05-17T20:19:16 EDT" duration-ms="13000" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method retried="true" signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" started-at="2025-05-17T20:19:16 EDT" name="checkOut" finished-at="2025-05-17T20:20:27 EDT" duration-ms="71144" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method signature="checkOut()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" started-at="2025-05-17T20:20:27 EDT" name="checkOut" finished-at="2025-05-17T20:21:38 EDT" duration-ms="70642" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test failed due to unexpected error.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC_04_CompletePurchase.checkOut(TC_04_CompletePurchase.java:78)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOut -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testCases.TC_04_CompletePurchase@60fa3495]" started-at="2025-05-17T20:21:38 EDT" name="closeApp" finished-at="2025-05-17T20:21:40 EDT" duration-ms="1475" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testCases.TC_04_CompletePurchase -->
    </test> <!-- edgeTest -->
  </suite> <!-- Suite -->
</testng-results>
