<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-V6E6QIF" failures="1" tests="5" name="testCases.TC05__AddToWishList" time="16.621" errors="0" timestamp="2025-05-17T20:22:14 EDT" skipped="2">
  <testcase classname="testCases.TC05__AddToWishList" name="addToWishList" time="7.739"/>
  <testcase classname="testCases.TC05__AddToWishList" name="addToWishList" time="6.938"/>
  <testcase classname="testCases.TC05__AddToWishList" name="addToWishList" time="0.319">
    <failure message="Test failed due to unexpected exception." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected exception.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC05__AddToWishList.addToWishList(TC05__AddToWishList.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- addToWishList -->
  <testcase classname="testCases.TC05__AddToWishList" name="addToWishList" time="0.891">
    <skipped/>
  </testcase> <!-- addToWishList -->
  <testcase classname="testCases.TC05__AddToWishList" name="addToWishList" time="0.734">
    <skipped/>
  </testcase> <!-- addToWishList -->
</testsuite> <!-- testCases.TC05__AddToWishList -->
