<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-V6E6QIF" failures="1" tests="4" name="testCases.TC03_AddToCart" time="10.194" errors="0" timestamp="2025-05-21T16:21:05 EDT" skipped="2">
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="1.909">
    <skipped/>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="0.079">
    <failure message="Test failed due to unexpected error." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Test failed due to unexpected error.
at org.testng.Assert.fail(Assert.java:111)
at testCases.TC03_AddToCart.testAddToCart(TC03_AddToCart.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </failure>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="0.064">
    <skipped/>
  </testcase> <!-- testAddToCart -->
  <testcase classname="testCases.TC03_AddToCart" name="testAddToCart" time="8.142"/>
</testsuite> <!-- testCases.TC03_AddToCart -->
